export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const SET_SUGGESTIONS_LOADING = 'SET_SUGGESTIONS_LOADING';
export const REMOVE_SUGGESTIONS_LOADING = 'REMOVE_SUGGESTIONS_LOADING';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const SET_WEATHER_DETAILS_LOADING = 'SET_WEATHER_DETAILS_LOADING';
export const REMOVE_WEATHER_DETAILS_LOADING = 'REMOVE_WEATHER_DETAILS_LOADING';
export const SET_WEATHER_DETAILS = 'SET_WEATHER_DETAILS';